notifications:
  email: false
services:
  - postgresql
  - docker
addons:
  postgresql: "9.4"
language: go
go_import_path: "miniflux.app"
go:
  - "1.11"
before_install:
  - npm install -g jshint
  - go get -u golang.org/x/lint/golint
  - docker build -t miniflux/rpmbuild -f rpmbuild/Dockerfile .
script:
  - jshint ui/static/js/*.js
  - make lint
  - make linux-amd64
  - export VER=`git describe --abbrev=0 --tags`
  - sed -i 's|^Version:.*$|Version: '"${VER}"'|' rpmbuild/SPECS/miniflux.spec
  - cp miniflux.1 LICENSE ChangeLog miniflux-linux-amd64 rpmbuild/SOURCES/
  - docker run --rm -v $(pwd)/rpmbuild:/root/rpmbuild  miniflux/rpmbuild rpmbuild -bb /root/rpmbuild/SPECS/miniflux.spec
  - cp rpmbuild/RPMS/*.rpm ./
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - "miniflux-linux-amd64"
    - "*.rpm"
  skip_cleanup: true
  on:
    tags: true
