notifications:
  email: false
services:
  - postgresql
  - docker
addons:
  postgresql: "9.4"
language: go
go_import_path: "miniflux.app"
go:
  - "1.11"
before_install:
  - npm install -g jshint
  - go get -u golang.org/x/lint/golint
script:
  - cd ui/static/js
  - jshint *.js
  - cd ../../../
  - make lint
  - make linux-amd64
  - export TRAVIS_TAG=`git describe --abbrev=0 --tags`
  - "echo \"Main version: ${TRAVIS_TAG}\""
  - "export SUBVER=`git rev-list \"${TRAVIS_TAG}\"..\"${TRAVIS_COMMIT}\" --count`"
  - export SUBVER=$(($SUBVER + 1))
  - "echo \"Minor version: ${SUBVER}\""
before_deploy:
  - cp miniflux.1 LICENSE ChangeLog miniflux-linux-amd64 rpmbuild/SOURCES/
  - "sed -i \"s|^Version:.*$|Version: ${TRAVIS_TAG}|\" rpmbuild/SPECS/miniflux.spec"
  - "sed -i \"s|^Release:.*$|Release: ${SUBVER}%{?dist}|\" rpmbuild/SPECS/miniflux.spec"
  - docker build -t miniflux/rpmbuild -f rpmbuild/Dockerfile .
  - docker run --rm -v $(pwd)/rpmbuild:/root/rpmbuild  miniflux/rpmbuild rpmbuild -bb /root/rpmbuild/SPECS/miniflux.spec
  - find ./rpmbuild -name '*.rpm' -exec cp {} ./ \;
  - export RPMF=$(find `pwd` -maxdepth 1 -name '*.rpm' -print -quit)
  - curl -v -F package=@${RPMF} https://${GEM_TOKEN}@push.fury.io/${GEM_USER}/
deploy:
  overwrite: true
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - "miniflux-linux-amd64"
    - "*.rpm"
  skip_cleanup: true
  on:
    branch: master
